VERSION 0.6
FROM golang:1.20.7-alpine
ENV GO111MODULE=on

deps:
    WORKDIR /scheduler
    COPY ../lib+artifact/* /lib/
    COPY --dir * .
    RUN go mod download

compile:
    FROM +deps
    RUN GOOS=linux GOARCH=amd64 go build -o bin/scheduler ./src
    SAVE ARTIFACT bin

    
update:
    FROM +deps
    RUN go get -u ./...
    SAVE ARTIFACT go.mod AS LOCAL go.mod
    SAVE ARTIFACT go.sum AS LOCAL go.sum