VERSION 0.6
FROM golang:1.20.6
ENV GO111MODULE=on

deps:
    WORKDIR /image
    COPY ../lib+artifact/* /lib/
    COPY go.mod go.sum ./
    RUN go mod download

compile:
    FROM +deps
    COPY ./src ./src
    RUN GOOS=linux GOARCH=amd64 go build -o bin/image ./src
    SAVE ARTIFACT bin AS LOCAL ./bin

    
update:
    FROM +deps
    RUN go get -u ./...
    SAVE ARTIFACT go.mod AS LOCAL go.mod
    SAVE ARTIFACT go.sum AS LOCAL go.sum