VERSION 0.6

FROM hashicorp/terraform:1.5


plan:
    RUN echo $AWS_ACCESS_KEY_ID
    WORKDIR /infra
    COPY --dir . /infra
    COPY ../functions/oracle+compile/* /functions/oracle/bin
    COPY ../functions/poll+compile/* /functions/poll/bin
    COPY ../functions/result+compile/* /functions/result/bin
    COPY ../functions/scheduler+compile/* /functions/scheduler/bin
    COPY ../functions/status+compile/* /functions/status/bin
    COPY ../functions/image+compile/* /functions/image/bin
    # RUN ls / && echo "num num num" && ls -alR /functions
    RUN --secret AWS_ACCESS_KEY_ID \
    --secret AWS_SECRET_ACCESS_KEY \
    --secret AWS_DEFAULT_REGION \
    --secret TF_VAR_OPENAI_API_KEY \
    terraform init -var-file="auto.tfvars"
    RUN --no-cache \ 
    --secret AWS_ACCESS_KEY_ID \
    --secret AWS_SECRET_ACCESS_KEY \
    --secret AWS_DEFAULT_REGION \
    --secret TF_VAR_OPENAI_API_KEY \
    terraform apply -auto-approve -var-file="auto.tfvars"
    SAVE ARTIFACT .terraform/ AS LOCAL .terraform/

destroy:
    WORKDIR /infra
    COPY --dir . /infra
    COPY ../functions/oracle+compile/* /functions/oracle/bin
    COPY ../functions/poll+compile/* /functions/poll/bin
    COPY ../functions/result+compile/* /functions/result/bin
    COPY ../functions/scheduler+compile/* /functions/scheduler/bin
    COPY ../functions/status+compile/* /functions/status/bin
    COPY ../functions/image+compile/* /functions/image/bin
    RUN --secret AWS_ACCESS_KEY_ID \
    --secret AWS_SECRET_ACCESS_KEY \
    --secret AWS_DEFAULT_REGION \
    --secret TF_VAR_OPENAI_API_KEY \
    terraform init -var-file="auto.tfvars"
    RUN --secret AWS_ACCESS_KEY_ID \
    --secret AWS_SECRET_ACCESS_KEY \
    --secret AWS_DEFAULT_REGION \
    --secret TF_VAR_OPENAI_API_KEY \
    terraform destroy -auto-approve -var-file="auto.tfvars"