VERSION 0.6
FROM golang:1.20-bullseye

deps:
    WORKDIR /libs/hello
    COPY go.mod go.sum ./
    RUN go mod download

artifact:
    FROM +deps
    COPY *.go .
    SAVE ARTIFACT .

update:
    FROM +deps
    RUN go get -u ./...
    SAVE ARTIFACT go.mod AS LOCAL go.mod
    SAVE ARTIFACT go.sum AS LOCAL go.sum