VERSION 0.6
FROM golang:1.20.6
ENV GO111MODULE=on
deps:
    WORKDIR /libs
    COPY go.mod go.sum ./
    RUN go mod download

artifact:
    FROM +deps
    COPY --dir * .
    SAVE ARTIFACT .

update:
    FROM +deps
    RUN go get -u ./...
    SAVE ARTIFACT go.mod AS LOCAL go.mod
    SAVE ARTIFACT go.sum AS LOCAL go.sum