VERSION 0.6
FROM golang:1.20.7-alpine
ENV GO111MODULE=on
deps:
    WORKDIR /oracle
    COPY ../lib+artifact/* /lib/
    COPY --dir * .
    RUN go mod download

test:
    FROM +deps
    RUN mkdir -p reports
    RUN go test ./... -coverprofile="coverage.out" -covermode="count" -json > reports/report.json
    RUN go tool cover -html="coverage.out" -o reports/coverage.html
    SAVE ARTIFACT reports/** AS LOCAL reports/


compile:
    FROM +deps
    COPY ./src ./src
    RUN GOOS=linux GOARCH=amd64 go build -o bin/oracle ./src
    SAVE ARTIFACT bin AS LOCAL ./bin

    
update:
    FROM +deps
    RUN go get -u ./...
    SAVE ARTIFACT go.mod AS LOCAL go.mod
    SAVE ARTIFACT go.sum AS LOCAL go.sum